# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Ubuntu Selenium Java

on:
  push:
    paths:
      - 'puppeteer/**'
      - '.github/workflows/ubuntu-selenium-java.yml'
  pull_request:
    paths:
      - 'puppeteer/**'
      - '.github/workflows/ubuntu-selenium-java.yml'

defaults:
  run:
    working-directory: puppeteer

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Disable AppArmor
      run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

    - name: Run tests
      run: ./setup.sh

    - name: list crashdumps
      if: always()
      run: ls ~/.config/google-chrome-for-testing/Crashpad/pending

    - name: Upload crash dumps
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: crash-dumps
        path: ~/.config/google-chrome-for-testing/Crashpad/pending/*.dmp

    - name: Bisect
      if: always()
      run: python3 ./bisect-builds.py --verify-range -v -cft --not-interactive --use-local-cache -g 145.0.7632.77 -b 146.0.7680.31 -c 'node test.mjs %p'